### PR TITLE
Mass upgrade dependencies

### PR DESCRIPTION
**Pull request by jacobq**
Things have gotten a bit dusty....
Closes https://github.com/EmberMN/ember-cli-plotly/issues/176

### CODE REVIEW

**Comment by jacobq** [comment]
Looks like my TravisCI integration stuff is out of date too.... oh well, I manually started a build here and we'll see how it goes:
https://travis-ci.com/github/EmberMN/ember-cli-plotly/builds/198984321

**Comment by lsmun** [comment]
If I'm reading the logs correctly, looks like the tests are failing from lint errors. I can get to them tomorrow if you can't today.

**Comment by jacobq** [comment]
> If I'm reading the logs correctly, looks like the tests are failing from lint errors. I can get to them tomorrow if you can't today.

Yes, I'm working on them. Most are fixed with `eslint --fix .`, but there are a handful of others to go through. Right now I'm fixing the waiter API.

**Comment by jacobq** [comment]
Well, the [`angle-brackets-codemod`](https://github.com/ember-codemods/ember-angle-brackets-codemod) let me down (either that or I was doing something dumb by mistake), so I bailed on attempting to change all the `{{}}` components to `<>`, etc. but that can be done separately. We should be able to at least get another version out with updated deps here.

**Pull request merged**
